project:
  type: website

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Data Science Lab"
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "[**Data Science Tools Final Project Check-In**](https://forms.office.com/e/75qEdyZbim) open! Deadline Sat, Nov 8."
  #   type: warning
  #   position: below-navbar
  margin-header: |
    ![Logo image](/img/datasciencelabicon.jpg)
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: schedule.qmd
    right:
      - icon: github
        href: "{{< var org.link >}}"
        text: "{{< var org.name >}}" 
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Syllabus"
        file: index.qmd
      - text: "Schedule"
        file: schedule.qmd
      - text: "Presentation Guide"
        file: presentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true



