---
title: "Schedule"
---

:::{.callout-important collapse=false appearance='default' icon=true}
## Developing Schedule
The schedule can be updated. Updates will be marked here and announced on Teams.
:::

# Tabular Schedule  {.unnumbered}

Class is **{{<var day>}}** in 2 consecutive Sessions **{{<var time>}}**      
Location: **{{<var room>}}** in-person if not stated otherwise 

Week | Dates  | What?                  | Where?                  |
-----|--------|------------------------|-------------------------|
1    | Feb 05 | [**Kick off the Lab**](https://docs.google.com/presentation/d/e/2PACX-1vQlilYye6gLj3-Ab2HIIi6q01GZwEV_NlG0VD1yO62rxO5KmVOhKvRMU21mhUVvTtXuIGKW4H2p73wl/pub?start=false&loop=false&delayms=3000) [Survey link](https://forms.office.com/e/E8c3HqRiY8)  | {{<var room>}}  |
2    | Feb 12 | [**Topics and Team Formation**](https://docs.google.com/presentation/d/e/2PACX-1vQVTQ_R5q5Ed69l8_3-uciMS8w1zuiL-0RNiuU12LG3I6UhmZ98g9OuL3qL1MdYFD2HDWCj8Gngz1pp/pub?start=false&loop=false&delayms=3000), Q&A | {{<var room>}}         |
3    | Feb 19 | 🧑‍💻 **Tutorial:** [Communicating and Reporting of Data Science Projects, Literature Management](tools_reporting_literature.qmd) | {{<var room>}}  |
4    | Feb 26 | *Individual meetings with student teams* | Online |
5    | Mar 05 | 1️⃣ **Student Proposal Presentations** [Presentation Guide](presentation.qmd) <br> **Schedule** (in private repo):[Teams](https://github.com/CU-S26-MSDSSB-DSCI-01-DataScienceLab/LabProjectTopicInput/blob/main/TEAMS.md) [Schedule](https://github.com/CU-S26-MSDSSB-DSCI-01-DataScienceLab/LabProjectTopicInput/blob/main/SCHEDULE.md) | {{<var room>}} |
6    | Mar 12 | *Individual meetings with student teams*  | Online |
7    | Mar 19 | 🧑‍💻 **Tutorial** [Collaboration, Data, Methods, Reporting](tutorial_data_methods.qmd) | {{<var room>}} |
8    | Mar 26 | *Individual meetings with student teams*  | Online or <br> {{<var room>}} |
     |        |     | Spring break           |        |
9    | Apr 09 | 2️⃣ **Student Progress and Learning Presentations**  [Presentation Guide](presentation.qmd)   | {{<var room>}}     |
10   | Apr 16 | 🧑‍💻 **Tutorial** Generate Text with AI, Avoid Bullshit  | {{<var room>}}     |
11   | Apr 23 | *Individual meetings with student teams* <br> | Online or  <br> {{<var room>}} |
12   | Apr 30 | *Individual meetings with student teams* <br> | Online or  <br> {{<var room>}}  |  {{<var room>}} |
13   | May 07 | 3️⃣ **Student Final Presentations ** [Presentation Guide](presentation.qmd)  | {{<var room>}} |

: {tbl-colwidths="[5, 15, 55, 25]"}

**Deadline** for Project Reports is the regular deadline in the [Academic Calendar]({{<var link.academic-calendar>}}), see the *Deadline for Students to Submit Assessments, Spring Semester*.